name: Devhub deployement
on:  [push]
jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Test
        run: 'ls -al ..'
      - name: Set variables
        run: 'echo "::set-env name=TEST_FILE::testResults-$(date).json"'
      - name: Decript
        run: openssl enc -d -aes-256-cbc -in ../TestCISalesforce/dev-hub-login.txt.enc -out ../TestCISalesforce/dev-hub-login.txt -k $DEVBOXPASS
      - name: Login devhub
        run: 'sfdx force:auth:sfdxurl:store -f dev-hub-login.txt -d -a Hub_Org'
      - name: Create scratch org
        run: 'sfdx force:org:create -f project-scratch-def.json -a pullReqTest'
      - name: Push data
        run: 'sfdx force:source:push -u pullReqTest'
      - name: Execute tests
        run: 'sfdx force:apex:test:run -c  -r json > $TEST_FILE'