name: Devhub deployement
on:  [push]
jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: 'ls -al ..'
      - name: Set variables
        run: 'echo "::set-env name=TEST_FILE::testResults-$(date).json"'
      - name: Decript
        working-directory: ${{ github.workspace }}
        run: openssl enc -d -aes-256-cbc -in dev-hub-login.txt.enc -out dev-hub-login.txt -md sha256 -k $DEVBOXPASS
      - name: Login devhub
        working-directory: ${{ github.workspace }}
        run: 'sfdx force:auth:sfdxurl:store -f dev-hub-login.txt -d -a Hub_Org'
      - name: Create scratch org
        working-directory: ${{ github.workspace }}
        run: 'sfdx force:org:create -f ./config/project-scratch-def.json -a scratchForTests'
      - name: Push data
        working-directory: ${{ github.workspace }}
        run: '\cp .forceignore_ci .forceignore && sfdx force:source:push -u scratchForTests'
      - name: Execute tests
        working-directory: ${{ github.workspace }}
        run: 'sfdx force:apex:test:run -c  -r json > testResults.json'
      - name: Delete scratch org
        run: 'sfdx force:org:delete -u scratchForTests'